### ISSUE TITLE
Feature Request: Add a Dockerfile

### ISSUE THREAD

**Issue by Djiit** [cherrypush/cherry#46]
Allow users to easily spin up Cherry using Docker

**Comment by Djiit** [comment]
Happy to work on it soon and push a PR :)

**Comment by fwuensche** [comment]
Hey! Thanks :) isn't it what you've already done in this PR?
https://github.com/cherrypush/cherry/commit/b8187d0bd9d20d7d52c84f1aba4a496d5acfa0c7
